### ISSUE TITLE
Clicking on a component in the DepMap triggers an animation that moves the diagram out of the screen.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/vscode-appland#106]
The behavior is not consistently reproducible, only seems to happen right after appmap file is opened. If the viewer has a vertical scroll bar (lots of events), the diagram's animation will have it scroll down out of the screen.

Likely related to issue https://github.com/applandinc/vscode-appland/issues/91

**Comment by dustinbyrne** [comment]
Fixed by https://github.com/applandinc/appmap-js/pull/49
