### ISSUE TITLE
Collect usage telemetry

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/vscode-appland#165]
https://www.npmjs.com/package/vscode-extension-telemetry

Send a telemetry event when a user opens an AppMap. It should contain:
- `metadata.language`
- `metadata.client`
- `metadata.frameworks`
- `metadata.git.url`
- number of events containing `http_server_request`
- number of events containing `sql_query`
- total number of events

**Comment by mcollum1** [comment]
@dustinbyrne 
Is there any way to get things like average time spent using the extension, etc.? Also, where will this data become available? 
Few examples I found: 
https://medium.com/@almenon214/adding-telemetry-to-your-vscode-extension-f3d52d2e573c
https://github.com/Almenon/AREPL-vscode/blob/master/src/telemetry.ts
