### ISSUE TITLE
Event count telemetry information is sent as a metric

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/vscode-appland#193]
`appmap.open` should send:
- `appmap.num_events`
- `appmap.num_http_events`
- `appmap.num_sql_events`
  
as metrics (numeric measure) instead of event properties.
https://github.com/Microsoft/vscode-extension-telemetry#sending-events

**Comment by kgilpin** [comment]
We do want a specific telemetry event when the user opens an AppMap for the
first time that:

Has an HTTP request
Has SQL
Has at least some threshold count of events (50?)
