### ISSUE TITLE
AppMap panel is stuck loading when no workspace is open

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/vscode-appland#196]
![image](https://user-images.githubusercontent.com/8737782/119566887-aa40d480-bd79-11eb-8f5e-3184723aaec9.png)

**Comment by ptrdvrk** [comment]
The start/stop recording function should be disabled when no project is open, too.
![image](https://user-images.githubusercontent.com/42008542/119849361-8ea10f80-beda-11eb-9670-66c727f6a788.png)

**Comment by kgilpin** [comment]
You could still create a recording and save the file to the filesystem,
couldn't you?

**Comment by ptrdvrk** [comment]
You could, but I don't think it is unreasonable to ask users to open a project/workspace before interacting with AppMaps. The edge cases will IMO become trickier to deal with when we add AppMap Cloud and additional advanced features.
