### ISSUE TITLE
Event: `appland.appmap/plugin:uninstall`

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/vscode-appland#210]

**Comment by sashahonchar** [comment]
@dustinbyrne According to [documentation](https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook) we can send `uninstall` event only with external JS file, but in this case we have to store API auth key in that file.

**Comment by kgilpin** [comment]
I don't think this is worth doing. When a user abandons using AppMap we
will be able to see that from telemetry already.

Whether they uninstalled the AppMap plugin isn't that important, compared
to knowing that they're inactive.

- kevin
