### ISSUE TITLE
Add short list of suggested maps to user

### ISSUE THREAD

**Issue by torchello** [applandinc/vscode-appland#273]
Currently we don't suggest anything:
![image](https://user-images.githubusercontent.com/897885/125662279-fc006020-d89f-4759-98fa-fb7decec8b87.png)

**Comment by dustinbyrne** [comment]
Added in https://github.com/applandinc/vscode-appland/pull/265/commits/5105d07e57c7241b74c193997b1bf8ebe809b4e5
