### ISSUE TITLE
WIP: List of improvements before Ruby soft launch

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/vscode-appland#277]
- [ ] List of appmaps to be populated with up to 10 good appmaps
- [ ] Flow for non-rails Ruby projects
- [ ] Flow for unsupported ruby, rails versions
- [ ] Flow for non-Ruby projects - what do we show?
- [ ] Review and cover all error states
- [ ] Flow for workspace with multiple projects
- [ ] Update "Using AppMaps" and "Mastering AppMaps" milestones with real links
- [ ] Reset steps 3 and 4 after steps 1 or 2 were re-visited
- [ ] Telemetry events
- [ ] Show message when user closes incomplete quickstart - "Close, Continue, Later?" 
- [ ] Step 3 after the first appmap has been recorded: allow re-running of steps but also show the Next step - needs UX review
- [ ] Cucumber tests cannot be stopped
- [ ] Count number of good appmaps in Step 3
- [ ] Test output sent to Terminal

**Comment by kgilpin** [comment]
As done as it will ever be.
