### ISSUE TITLE
Ruby project not detected for a rails app with JavaScript components

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/vscode-appland#278]
huginn app: https://github.com/huginn/huginn

![image](https://user-images.githubusercontent.com/42008542/126011622-35968f68-a63b-41c9-a09a-a40793c5c70a.png)

**Comment by dustinbyrne** [comment]
This is a bit of a philosophical question. If the project is 75% JavaScript, is the project in question actually still a Ruby project?

I've added a change in #292 to only return supported languages. With this change, it'll now report the repository as a Ruby project. However, when JavaScript is added in the future, it'll begin reporting it as JavaScript.

**Comment by ptrdvrk** [comment]
Thank you @dustinbyrne , I think this is a good solution for now. When we have JavaScript, users will be able to pick which language they want to map.
