### ISSUE TITLE
[Onboarding] Quickstart window opens automatically in every case after first install

### ISSUE THREAD

**Issue by Daniel-Warner-X** [applandinc/vscode-appland#317]
Open the Quickstart on extension install no matter what the conditions. For the Python user in the video (Windows OS) the Quickstart window did not automatically open. He installed the extension into a workspace with no project and then opened a project. He should have gotten the default 'no language' page.

https://user-images.githubusercontent.com/1229326/128262468-02a6af0e-502b-4db9-ad3b-913cff07bff5.mov

**Comment by torchello** [comment]
Unable to reproduce. Closing until we see it again.
