### ISSUE TITLE
[Onboarding] Remove the rectangular, blue  'Install agent' from the web view

### ISSUE THREAD

**Issue by Daniel-Warner-X** [applandinc/vscode-appland#318]
After a user has installed the agent, the ‘Install agent’ button in the sidebar (tree view) persists. We have seen users click it repeatedly expecting something to happen. Most recently we watched a user go through the entire agent installation a second time thinking that it hadn't worked because the button was still there.

It is doing more harm than good... get rid of it.

![image](https://user-images.githubusercontent.com/1229326/128256454-28559fd1-052c-448f-a40e-82de8b88a318.png)

**Comment by torchello** [comment]
```
@Petr and I agree that it should be changed to 'Open quickstart documentation' and should link to https://appland.com/docs/quickstart/
```
