### ISSUE TITLE
Command exists to open AppMap with given state

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/vscode-appland#336]
As a user, I'd like to be able to click a link in my terminal to open an AppMap at a specific spot. 

Given the command `appland.appmap/open`, and the following parameters:
`uri`: the URI to open
`state`: the state to be set upon initializing the AppMap view

Then I can generate a link to pop open the AppMap viewer in VSCode at ta specific spot:
vscode://appland.appmap/open?uri=%2Fhome%2Fdb%2Fdev%2Fspring-projects%2Fspring-petclinic%2Fbuild%2Fappmap%2FMy%20data.appmap.json&state=%7B%22currentView%22%3A%22viewFlow%22%2C%22selectedObject%22%3A%22event%3A2%22%7D

**Comment by sashahonchar** [comment]
@dustinbyrne Looks like it's not possible to open file with custom query params.
Official docs: https://code.visualstudio.com/docs/editor/command-line#_opening-vs-code-with-urls

**Comment by dustinbyrne** [comment]
Here are some resources that I've found:
- Activating the extension upon opening an extension URI: https://code.visualstudio.com/api/references/activation-events#onUri
- [`vscode.window`](https://code.visualstudio.com/api/references/vscode-api#window) contains a method `registerUriHandler` which looks to provide the behavior we need

**Comment by sashahonchar** [comment]
Done: https://github.com/applandinc/vscode-appland/pull/232/commits/4ef7456925f1154d7cc3145eba11ed70a10a735f
