### ISSUE TITLE
[UI Cleanup] HTTP requests and related visual components are styled purple instead of red

### ISSUE THREAD

**Issue by Daniel-Warner-X** [applandinc/vscode-appland#342]
Change HTTP Requests and the related UI elements from red to purple (#542168).

Red has a very specific meaning in VSCode, JetBrains IDE's, and applications in general. Let's try purple and see how that feels. Green could also work for HTTP requests.

![image](https://user-images.githubusercontent.com/1229326/130684580-9d25f540-f975-448a-b7e5-17aebf8ecae4.png)

**Comment by Daniel-Warner-X** [comment]
In the storybook the sidebar item is purple but the diagram is still red: 
![image](https://user-images.githubusercontent.com/1229326/131711104-33418478-46c6-4e30-a351-261241638cb4.png)

**Comment by sashahonchar** [comment]
Try to run `yarn build` before running Storybook. @Daniel-Warner-X 
I changed HTTP color in `packages/diagrams` package and you need to rebuild dependencies.

This is how it looks:

![image](https://user-images.githubusercontent.com/1647695/131718251-f1438558-ec76-459e-abb7-b165bf369e08.png)
