### ISSUE TITLE
The gray used for 'Labels' has an accessible level of contrast.

### ISSUE THREAD

**Issue by Daniel-Warner-X** [applandinc/vscode-appland#343]
The gray used for 'LABELS' needs to be darker...

![image](https://user-images.githubusercontent.com/1229326/130685515-bbe72ee6-b197-4464-b119-a091db61aafb.png)

**Comment by Daniel-Warner-X** [comment]
The gray is still a little too light.... 
![image](https://user-images.githubusercontent.com/1229326/131711325-07356636-5679-4aaa-b249-28d670dc77d4.png)

**Comment by sashahonchar** [comment]
Fixed
