### ISSUE TITLE
Users can navigate into node details in side panel

### ISSUE THREAD

**Issue by typaulhus** [applandinc/vscode-appland#42]
When selecting a node in the component diagram, its details will be displayed in the sidebar. Users will be able to view the source code, view individual function details, or go back to the component diagram

![component-node-selected](https://user-images.githubusercontent.com/123787/103705405-f5984900-4f78-11eb-8dc6-b8d0d6d2ea22.png)

![component-function-details](https://user-images.githubusercontent.com/123787/103705413-f7faa300-4f78-11eb-8691-dd03938ba2be.png)

[Figma -> ](https://www.figma.com/proto/BqZuGL8egIF37cgbvrz1Xm/vscode?node-id=112%3A1277&viewport=663%2C774%2C0.4290641248226166&scaling=min-zoom)

**Comment by typaulhus** [comment]
when clicking into a related function here, should the map change to the event view for that function? This is how we're treating that interaction when clicking on an connection edge

**Comment by kgilpin** [comment]
Should only change to the event view when the user clicks an event.

Clicking an edge should not change to the event view. It should list the
events for that edge in the details panel.

**Comment by typaulhus** [comment]
loom: https://www.loom.com/share/3dd864c131d94e72ac85a0479b27b43c
