### ISSUE TITLE
AppMap Crashes VSCode

### ISSUE THREAD

**Issue by nocibambi** [applandinc/vscode-appland#452]
Type: <b>Bug</b>

# Steps to reproduce
1. Have the AppMap extension installed in VSCode
2. Start up VSCode

**Result**: VSCode crashes within 30-40 seconds

After disabling AppMap, VScode does not crash any more.

# Expected result
No crash

Extension version: 0.40.0
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:25.715Z)
OS version: Linux x64 5.15.0-46-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|15.51GB (3.65GB free)|
|Process Argv|--crash-reporter-id cdf15171-adb3-4f7e-8f1f-3b1a38af2c8c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by ahtrotta** [comment]
Hi András, I haven't been able to reproduce this on my system. I'm using Ubuntu 20.04.4 with:

Extension version: 0.40.0
VS Code version: 1.70.2
OS version: Linux x64 5.4.0-124-generic

Do you have any other extensions installed?

**Comment by nocibambi** [comment]
I have plenty of extensions, but I identified AppMap with [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect), which, in theory, disables all the other ones in the process.

However, I just upgraded to Ubuntu 22.04 two days ago, so that might have something to do with it...

**Comment by ahtrotta** [comment]
Okay, good to know, thank you! I'll look into this.

**Comment by ahtrotta** [comment]
Hi András, I did a fresh install of Ubuntu 22.04 and I still can't reproduce the issue:

Extension version: 0.40.0
VS Code version: 1.70.2
OS version: Linux x64 5.15.0-46-generic

I have a few questions for you:

1. What language are you working with?
2. Are you working in a large workspace with large projects of multiple projects? If so, could you try using a smaller workspace? A useful workspace for testing is the [Rails sample app](https://github.com/land-of-apps/sample_app_6th_ed).
3. Could you provide more configuration information about the A/B Experiments?
4. This is a shot in the dark, but could you try running VS Code with [gpu acceleration turned off](https://stackoverflow.com/questions/29966747/how-can-i-disable-gpu-rendering-in-visual-studio-code)?

**Comment by nocibambi** [comment]
Now, it disappeared and I cannot reproduce it. :sweat_smile: 

1. Python
2. It was a single-file script creating a dash/plotly dashboard with venv information, a reqs file, and a backup script.
3. There was nothing really anything to configure with the A/B test. I just ran it, and each time VSCode crashed, I restarted VSCode and told Bisect that 'This is bad'.

**Comment by ahtrotta** [comment]
Okay, great to hear that it disappeared! Let me know if you have any other problems!
