### ISSUE TITLE
"Reset View" shifts the diagram towards the bottom of the page if the list the page has a vertical scroller.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/vscode-appland#91]
If the list of objects in the nav bar is long and triggers a page scrollbar, the "Reset view" action seems to center the diagram vertically for the total page height, shifting it towards the bottom of the page. 

![image](https://user-images.githubusercontent.com/42008542/105413245-d6015180-5c03-11eb-8a46-ebff167dede2.png)

**Comment by dustinbyrne** [comment]
Fixed by https://github.com/applandinc/appmap-js/pull/49
