### ISSUE TITLE
Flow view: rendering issues when only single event is present.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/vscode-appland#92]
See 2:41 in the video: https://applanding.slack.com/files/UF8JH75RP/F01KYF26BJM/edward_zhao__appland_-_cin-service_-_visual_studio_code_2021-01-22_23-31-09.mp4

**Comment by sashahonchar** [comment]
@ptrdvrk , Could you send me that appmap json file?

**Comment by ptrdvrk** [comment]
Let me see if I can get you one. We've seen this problem with one of our test users.
