### ISSUE TITLE
30-second video walk-though of Troubleshooting use case.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/vscode-appland#93]

**Comment by kgilpin** [comment]
Let’s call this Debugging

Troubleshooting sounds like troubleshooting AppLand itself

**Comment by dustinbyrne** [comment]
@ptrdvrk is this still relevant?

**Comment by ptrdvrk** [comment]
It is but on a back burner for now, I'll revisit it a bit later. Moving to backlog for now.
